version: '3'

services:
  base:
    build:
      context: base
      args:
        num_jobs: 2
    image: ghcr.io/mfem/containers/base:latest

  cpu:
    build:
      context: cpu
      args:
        num_jobs: 2
        hypre_version: 2.27.0
    image: ghcr.io/mfem/containers/cpu:latest

  cuda:
    build:
      context: cuda
      args:
        num_jobs: 2
        cuda_arch_sm: 70
        hypre_version: 2.27.0
    image: ghcr.io/mfem/containers/cuda:latest
