services:
  base:
    build:
      context: base
      args:
        num_jobs: 8
    image: ghcr.io/mfem/containers/base:latest

  cpu:
    build:
      context: cpu
      args:
        num_jobs: 8
        hypre_version: 2.31.0
    image: ghcr.io/mfem/containers/cpu:latest

  cpu-tpls:
    build:
      context: cpu-tpls
      args:
        num_jobs: 8
    image: ghcr.io/mfem/containers/cpu-tpls:latest

  cuda:
    build:
      context: cuda
      args:
        num_jobs: 8
        cuda_arch_sm: 89
        hypre_version: 2.31.0
    image: ghcr.io/mfem/containers/cuda:latest

  developer-cpu:
    build:
      context: developer
      args:
        base_image: cpu-tpls
        num_jobs: 8
    image: ghcr.io/mfem/containers/developer-cpu:latest

  developer-cuda:
    build:
      context: developer
      args:
        base_image: cuda
        num_jobs: 8
        cuda_arch_sm: 89
    image: ghcr.io/mfem/containers/developer-cuda:latest
